// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAberHN3y7ihkhHXIODxo-9T_FjrFuYL1U',
    appId: '1:569709823219:web:9164321285398316b06386',
    messagingSenderId: '569709823219',
    projectId: 'shopping-app-16788',
    authDomain: 'shopping-app-16788.firebaseapp.com',
    databaseURL: 'https://shopping-app-16788-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-16788.firebasestorage.app',
    measurementId: 'G-N8TNV73DCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9RTOApiUxNoOj_WaubjKEZH_DDyqKwaE',
    appId: '1:569709823219:android:3fd302cd97f95a61b06386',
    messagingSenderId: '569709823219',
    projectId: 'shopping-app-16788',
    databaseURL: 'https://shopping-app-16788-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-16788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuaUKj0V5SuoBlEnfUtnC5y_igXpPikns',
    appId: '1:569709823219:ios:953df83e61affaabb06386',
    messagingSenderId: '569709823219',
    projectId: 'shopping-app-16788',
    databaseURL: 'https://shopping-app-16788-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-16788.firebasestorage.app',
    iosClientId: '569709823219-edd2ee343ofv5u2h3ld17kfdh2bkdm0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuaUKj0V5SuoBlEnfUtnC5y_igXpPikns',
    appId: '1:569709823219:ios:953df83e61affaabb06386',
    messagingSenderId: '569709823219',
    projectId: 'shopping-app-16788',
    databaseURL: 'https://shopping-app-16788-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-16788.firebasestorage.app',
    iosClientId: '569709823219-edd2ee343ofv5u2h3ld17kfdh2bkdm0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAberHN3y7ihkhHXIODxo-9T_FjrFuYL1U',
    appId: '1:569709823219:web:7210c6587b400929b06386',
    messagingSenderId: '569709823219',
    projectId: 'shopping-app-16788',
    authDomain: 'shopping-app-16788.firebaseapp.com',
    databaseURL: 'https://shopping-app-16788-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shopping-app-16788.firebasestorage.app',
    measurementId: 'G-SJ7K1N1JNS',
  );
}
